### PR TITLE
Add enhancements by @rvora

### PR DESCRIPTION
**Pull request by arnisoph**

### CODE REVIEW

**Comment by rvora** [comment]
There are a lot of changes here. Summary below, examples added to pillar.example. Your directory and files structure has changed quite a bit in the meantime so a lot would have to be manually merged in. All of this has been tested only on CentOS 6.x

Main features added are to automatically add records from Mine and automatically delegate (slave) zones using data in Mine or Grains.

* had to change some basic zone file syntax to make it work on CentOS (like adding $ORIGIN)
  * things worked without these changes but ActiveDirectory could not work with this nameserver as a slave unless I added the changes.
* Added ability to include files in zone file (not named.conf) using the $INCLUDE directive
  * this allows one to manage parts of zonefile externally (used intrinsically by features below)
* **zone_recs_from_mine**: all records from mine matching zone domain are added to zone file
  * mine needs to be configured to send network.ip_addrs as per salt mine documentation
  * Reactor can then be configured to run binddns state on the nameservers when minion starts 
  * this allows for DNS records to be created and destroyed for ephemeral minions
  * This example will automatically add records from mine matching *.example.com to /var/named/data/in.example.com which is $INCLUDEd in /var/named/data/db.example.com
```
  zones:
    - create_db_only: True
      name: example.com
      soa: ns1.example.com
      zone_recs_from_mine: True
```

* **auto_delegate_from_mine** (nameserver_match, match_type): Look for network.ip_addrs for minions matching nameserver_match using match_type (default glob) add zone delegation records (NS and A)
  * Allows ephemeral DNS servers to be auto-delegated
  * This will become the preferred method over auto_delegate_from_grain once mine data can be sent upstream from syndics to master-of-masters
  * This example will automatically add NS (delegation) and A (glue) records for ns1.foo.example.com and ns1.bar.example.com from Salt Mine to /var/named/data/in.example.com which in $INCLUDEd in /var/named/data/db.example.com
```
  zones:
    - create_db_only: True
      name: example.com
      soa: ns1.example.com
      auto_delegate_from_mine:
         - nameserver_match: ns\w*\..*\.example.com
         - match_type: pcre
```
* **auto_delegate_from_grain** (grain): Similar but data is obtained from /etc/salt/grains of the minion running binddns state. Name of the grain is passed in the "grain" key.
  * Useful in case of a tree of masters (using syndic). Currently, syndics don't pass mine data up the chain but master-of-masters can discover all the minions in the tree configured with binddns using compound targeting. So master-of-masters can run a custom Runner to populate /etc/salt/grains for the top level nameservers with (FQDN, network.ip_addrs) triggered using Reactor, cron or some other method. 
  * This example will automatically add NS (delegation) and A (glue) records for ns1.foo.example.com and ns1.bar.example.com from salt['grains'].get('nameservers') on the minion running binddns formula on ns1.example.com (top-level nameserver) to /var/named/data/in.example.com which in $INCLUDEd in /var/named/data/db.example.com
```
  zones:
    - create_db_only: True
      name: example.com
      soa: ns1.example.com
      auto_delegate_from_grains:
         - grain: nameservers
```
Salt Runner to populate ns1.example.com:/etc/salt/grains can be done something like this:

```Python
import salt.client

def save(sublevel_match='ns\w*\..*\.example.com, sublevel_expr='pcre',
         toplevel_match='ns\w*\.example.com', toplevel_expr='pcre',
         grain_key='nameservers'):
  """Save ip_addrs of all sublevel_match minions to grains on minions specified by toplevel_match

  /etc/salt/grains (on ns1.example.com):
  nameservers:
    ns1.foo.example.com
      - 1.1.1.1
    ns2.foo.example.com
      - 2.2.2.2
    ns1.bar.example.com
      - 3.3.3.3
  """
  client = salt.client.LocalClient(__opts__['conf_file'])
  # allow for longer timeout for far-flung syndics to respond
  minions = client.cmd(sublevel_match, 'network.ip_addrs', expr_form=sublevel_expr, timeout=5)
  client.cmd(toplevel_match, 'grains.setvals', [{grain_key: minions}], expr_form=toplevel_expr)
```

And then execute runner on master-of-master
```bash
salt-run nameservers.save
```

Now running highstate on ns*.example.com (top-level nameservers) will auto-delegate to the sub-zones.

**Comment by bechtoldt** [comment]
@rvora wow, your PR is impressive. Would you be so kind to rebase your commits with the current state of the master branch?

I'll review your changes in a few days.

**Comment by bechtoldt** [comment]
Please also squash them to one single commit. Thanks!

**Comment by bechtoldt** [comment]
ping @rvora

**Comment by rvora** [comment]
Sorry... have been swamped... I'll try to get this done in a day or so.

Rajul

**Comment by arnisoph** [comment]
Thanks for the updates!

**Pull request merged**
